### ISSUE TITLE
connection timed out

### ISSUE THREAD

**Issue by mattdonkin** [jimdoescode/CodeIgniter-YouTube-API-Library#10]
Hi Jim,

I'm sometimes getting the following warning from the library. If I reload the same page it may or may not show the warning again. So far I've noticed this in Firefox only.

``` php

Severity: Warning

Message: stream_socket_client() [function.stream-socket-client]: unable to connect to tcp://gdata.youtube.com:80 (Connection timed out)

Filename: libraries/Youtube.php

Line Number: 125
```

**Comment by jimdoescode** [comment]
This sounds like it is a connectivity issue with your server and the YouTube servers. I know that YouTube does deny requests if too many are made in a consecutive manner. The browser you use shouldn't have anything to do with it, since it's a server to server transaction.

The library is just alerting you to the fact that it could not establish a connection to the YouTube api server. If you set the DEBUG flag to true you may get some more detailed information in the log which might help you pinpoint whats going on.

If you pin down the problem let me know. If it does turn out to be an issue with the library I will definitely fix it but at this point I think it has more to do with either your server or YouTube's servers.

I am going to close this issue as the connection code has been in use since the inception of the library and AFAIK the majority of users haven't been seeing this.

**Comment by mattdonkin** [comment]
Thanks for the prompt reply, I'll set the flag and see what it returns.
